### ISSUE TITLE
Exception: Cannot parse GALX!

### ISSUE THREAD

**Issue by elibus** [elibus/j-google-trends-client#1]
Exception in thread "main" org.freaknet.gtrends.client.exceptions.HierarchicalDownloaderException: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:130)
    at org.freaknet.gtrends.client.App.main(App.java:66)
Caused by: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
    at org.freaknet.gtrends.api.GoogleTrendsClient.execute(GoogleTrendsClient.java:78)
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:100)
    ... 1 more
Caused by: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
    at org.freaknet.gtrends.api.GoogleAuthenticator.galx(GoogleAuthenticator.java:118)
    at org.freaknet.gtrends.api.GoogleAuthenticator.authenticate(GoogleAuthenticator.java:82)
    at org.freaknet.gtrends.api.GoogleTrendsClient.execute(GoogleTrendsClient.java:66)
    ... 2 more

**Comment by elibus** [comment]
Fixed in API 1.4 and client 1.2.1
