### ISSUE TITLE
Can't login with my google account

### ISSUE THREAD

**Issue by cyberrob-zz** [elibus/j-google-trends-client#3]
I'm not sure if my google account is right for accessing google trend. It showed lots of web page elements in the cmd. Where can I get a google account that is workable?

```
,,[[1,"https://accounts.google.com/b/0/UpdateAccountRecoveryOptions?hl\u003dzh_TW",0,0,0]
,[3,"https://support.google.com/hangouts/?hl\u003dzh_TW\u0026authuser\u003d0#topic\u003d2944848",1,1,0]
,[8,"https://fiber.google.com/myfiber?hl\u003dzh_TW\u0026authuser\u003d0",1,1,1]
,[7,"https://plus.google.com/101430918515377000004/about?hl\u003dzh_TW\u0026authuser\u003d0",1,0,1]
,[4,"https://plus.google.com/settings/plus?hl\u003dzh_TW\u0026authuser\u003d0",1,1,0]
,[5,"https://www.google.com/voice?hl\u003dzh_TW\u0026authuser\u003d0#phones",0,0,1]
]
]
});</script><script>loadTimer.tick('idp');</script></body></html>

    at org.freaknet.gtrends.api.GoogleAuthenticator.login(GoogleAuthenticator.java:166)
    ... 4 more
```

**Comment by elibus** [comment]
Can you please copy/paste the full stack trace?
Version of the client you are using?

**Comment by cyberrob-zz** [comment]
I'm using version 1.2.4. The command basically print out I think it's a whole web page after login to Google. And there's only one line stack trace just like I posted.

I'm guesting if it's re-directed to other page not expected in the code. 

```
java -jar j-google-trends-client-1.2.4-jar-with-dependencies.jar -p [account] -u [pwd] -q kindle -d ~/gTrend
```

**Comment by elibus** [comment]
I know what it does print but if you want me to help you out whit this in gonna need it :)

**Comment by cyberrob-zz** [comment]
I can't output all logs into a file so here's part of it
https://gist.github.com/f12d6b1b3cba5093c05c.git

**Comment by elibus** [comment]
can't see it

**Comment by elibus** [comment]
I have just commited a new versiont. Can you try that out?

**Comment by cyberrob-zz** [comment]
I pulled j-google-trend-client and j-google-trend-api and here's the outcome:

```
robertwang@Robert-Wang [03:05:33] [~/Dropbox/Code/github/j-google-trends-client/releases/org/freaknet/gtrends/client/j-google-trends-client/1.2.5] [master]
-> % java -jar j-google-trends-client-1.2.5-jar-with-dependencies.jar -u [GMAIL] -p [PWD] -q "ardibao" -d ~/gTrendRepo
二月 23, 2014 3:05:58 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #1, ardibao
Exception in thread "main" java.lang.NullPointerException
    at java.io.StringReader.<init>(StringReader.java:50)
    at org.freaknet.gtrends.api.GoogleTrendsCsvParser.getSectionAsStringList(GoogleTrendsCsvParser.java:115)
    at org.freaknet.gtrends.client.HierarchicalDownloader.enqueueTopSearches(HierarchicalDownloader.java:170)
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:122)
    at org.freaknet.gtrends.client.App.main(App.java:64)
```

**Comment by elibus** [comment]
What's your Google locale setting?
Can you please manually download a CSV from google trend and send it over?

**Comment by elibus** [comment]
Looks like Google is making my life hard. They have some kind of bot detection. Working on it.
Thanks for the feedback.

**Comment by cyberrob-zz** [comment]
I believe my locale setting should be zh-TW. 
Here's the csv file: https://www.dropbox.com/s/i6zyyle255ywqn0/report.csv

Thanks for your hard work!!!

**Comment by elibus** [comment]
Looks like Google changed its policy. They have some kind of bot detection now that applies the bandwidth limit to logged user as well. I did not figure out how to solve this issue.

**Comment by cyberrob-zz** [comment]
Thanks for the hard work though. Using your own account is workable?

**Comment by elibus** [comment]
The login issue has been fixed. To make it work you need to set your locale to English

**Comment by elibus** [comment]
Can you please give a try at the last version?

**Comment by cyberrob-zz** [comment]
I'm not changing my locale for now, but it seems work!

```
robertwang@Robert-Wang [02:29:48] [~/Dropbox/Code/github/j-google-trends-client/releases/org/freaknet/gtrends/client/j-google-trends-client/1.2.6] [master]
-> % java -jar ./j-google-trends-client-1.2.6-jar-with-dependencies.jar -u account -p pwd -q "jobs -'steve jobs'" -m 100 -d ~/Dev/j-google-trends
三月 24, 2014 2:30:21 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #1, jobs -'steve jobs'
三月 24, 2014 2:30:32 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #2, job
三月 24, 2014 2:30:43 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #3, nhs jobs
三月 24, 2014 2:30:55 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #4, uk jobs
三月 24, 2014 2:31:06 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #5, nhs
三月 24, 2014 2:31:17 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #6, part time jobs
三月 24, 2014 2:31:29 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #7, online jobs
三月 24, 2014 2:31:42 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #8, government jobs
三月 24, 2014 2:31:53 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #9, bank jobs
三月 24, 2014 2:32:05 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #10, craigslist
三月 24, 2014 2:32:16 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #11, google jobs
...
...
三月 24, 2014 2:47:55 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #98, job centre vacancies
三月 24, 2014 2:48:05 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #99, jobcentre plus
三月 24, 2014 2:48:16 下午 org.freaknet.gtrends.client.HierarchicalDownloader start
資訊: #100, manager job description

robertwang@Robert-Wang [03:01:35] [~/Dev/j-google-trends]
-> % ll | wc -l
101
```

And here's content of csv file:

```
robertwang@Robert-Wang [03:09:34] [~/Dev/j-google-trends]
-> % cat steve\ jobs.csv
Web Search interest: steve jobs
Worldwide; 2004 - present

Interest over time
Month,steve jobs
2004-01,1
2004-02,1
2004-03,1
2004-04,1
2004-05,1
2004-06,1
2004-07,1
2004-08,1
2004-09,1
2004-10,1
2004-11,1
2004-12,1
2005-01,1
2005-02,1
2005-03,1
2005-04,1
2005-05,1
2005-06,1
2005-07,1
2005-08,1
2005-09,1
2005-10,1
2005-11,1
2005-12,1
2006-01,2
2006-02,1
2006-03,1
2006-04,1
2006-05,1
2006-06,1
2006-07,1
2006-08,1
2006-09,1
2006-10,1
2006-11,1
2006-12,1
2007-01,2
2007-02,1
2007-03,1
2007-04,1
2007-05,2
2007-06,2
2007-07,1
2007-08,1
2007-09,1
2007-10,1
2007-11,1
2007-12,1
2008-01,2
2008-02,1
2008-03,1
2008-04,1
2008-05,1
2008-06,2
2008-07,1
2008-08,1
2008-09,1
2008-10,1
2008-11,1
2008-12,1
2009-01,3
2009-02,1
2009-03,1
2009-04,1
2009-05,1
2009-06,2
2009-07,1
2009-08,1
2009-09,1
2009-10,1
2009-11,1
2009-12,1
2010-01,2
2010-02,2
2010-03,1
2010-04,2
2010-05,2
2010-06,3
2010-07,2
2010-08,1
2010-09,2
2010-10,2
2010-11,2
2010-12,2
2011-01,4
2011-02,6
2011-03,3
2011-04,2
2011-05,2
2011-06,3
2011-07,2
2011-08,12
2011-09,4
2011-10,100
2011-11,10
2011-12,7
2012-01,6
2012-02,5
2012-03,4
2012-04,4
2012-05,3
2012-06,3
2012-07,3
2012-08,3
2012-09,4
2012-10,5
2012-11,3
2012-12,3
2013-01,3
2013-02,3
2013-03,2
2013-04,2
2013-05,2
2013-06,3
2013-07,2
2013-08,5
2013-09,5
2013-10,4
2013-11,4
2013-12,3
2014-01,3
2014-02,3
2014-03,3


Top regions for steve jobs
Region,steve jobs
Singapore,100
United States,90
Hong Kong,82
Honduras,79
Lebanon,76
Philippines,74
Canada,73
Nepal,73
Mexico,70
Puerto Rico,70
India,69
Colombia,68
Guatemala,65
Nicaragua,65
Sri Lanka,65
Paraguay,63
Kenya,61
Dominican Republic,61
Italy,59
Trinidad and Tobago,58
Uganda,58
Iceland,56
El Salvador,56
Ecuador,56
Australia,56
Ghana,56
South Africa,55
Malaysia,54
Brunei,54
Malta,52
United Arab Emirates,52
Mongolia,50
Macau,50
Panama,50
Angola,50
Zimbabwe,49
Costa Rica,49
New Zealand,48
Armenia,48
Uruguay,48
United Kingdom,47
Albania,46
Macedonia (FYROM),46
Cambodia,46
Bolivia,45
Ireland,45
Jamaica,45
Pakistan,43
Brazil,43
Sweden,43
Mauritius,43
Norway,43
Bangladesh,42
Estonia,42
Switzerland,41
Luxembourg,41
South Korea,41
Czech Republic,41
Argentina,40
Qatar,40
Cyprus,39
Netherlands,38
Portugal,38
Georgia,38
Spain,37
Chile,37
Nigeria,36
Denmark,35
Bahrain,35
Senegal,35
Austria,34
Tanzania,34
Germany,34
Kuwait,34
Belgium,33
Hungary,33
Peru,32
Venezuela,32
Romania,32
Greece,30
France,29
Indonesia,29
Slovenia,29
Slovakia,29
Taiwan,28
Moldova,28
Croatia,28
Réunion,27
Oman,26
Latvia,26
Vietnam,26
Tunisia,25
Morocco,25
Serbia,24
Poland,23
Finland,22
Jordan,22
Bulgaria,22
Lithuania,21
Azerbaijan,21
Algeria,21
Bosnia and Herzegovina,20
Turkey,19
Israel,19
Iran,19
Kazakhstan,16
Saudi Arabia,15
Thailand,15
Egypt,14
Russia,10
China,10
Ukraine,9
Iraq,9
Belarus,8
Japan,8


Top cities for steve jobs
City,steve jobs
San Francisco (United States),100
New York (United States),87
Singapore (Singapore),84
Bangalore (India),79
Los Angeles (United States),67
Chicago (United States),63
Toronto (Canada),62
Mumbai (India),58
Washington (United States),56
Houston (United States),55
Bogotá (Colombia),55
Dallas (United States),53
Seattle (United States),52
Mexico City (Mexico),51
Atlanta (United States),44



Top searches for steve jobs
apple jobs,100
apple steve jobs,100
bill gates,60
steve jobs quotes,30
biography steve jobs,30
steve jobs stanford,25
steve jobs speech,25
steve jobs died,20
steve jobs dead,20
steve jobs death,20
steve jobs movie,15
wiki steve jobs,15
biografia steve jobs,15
steve wozniak,15
steve jobs cancer,15
steve jobs book,10
steve jobs frases,10
steve jobs pdf,10
steve jobs video,10
steve jobs wikipedia,10
steve job,10
steve jobs health,10
ashton kutcher,10
steven jobs,10
steve jobs quote,10
steve jobs news,10
steve jobs discurso,10
steve jobs wife,10
steve jobs house,5
steve jobs twitter,5
steve jobs keynote,5
steve jobs young,5
steve jobs presentation,5
steve jobs family,5
steve jobs yacht,5
steve jobs pixar,5
steve jobs next,5
steve jobs resigns,5
fake steve jobs,5
steve jobs muerte,5
steve jobs interview,5
steve jobs email,5
steve jobs murio,5
mark zuckerberg,5



Rising searches for steve jobs
steve jobs dead,Breakout
steve jobs death,Breakout
steve jobs died,Breakout
steve jobs speech,Breakout
steve jobs stanford,Breakout
wiki steve jobs,Breakout
steve jobs quotes,+200%
biografia steve jobs,+150%
steve jobs movie,+80%
```

**Comment by elibus** [comment]
Good :+1:
