### ISSUE TITLE
I get "reached your quota limit" every time.

### ISSUE THREAD

**Issue by waissbluth** [elibus/j-google-trends-client#5]
Hello, I'm getting a `GoogleTrendsClientException` every time I try to load data. Has there been a change in the API or something?

```
Exception in thread "main" org.freaknet.gtrends.client.exceptions.HierarchicalDownloaderException:      
org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: *** You are running too fast man!         
Looks like you reached your quota limit. Wait a while and slow it down with the '-S' option! *** 
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:129)
    at org.freaknet.gtrends.client.App.main(App.java:81)
Caused by: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: *** You are running too fast man! Looks like you reached your quota limit. Wait a while and slow it down with the '-S' option! *** 
    at org.freaknet.gtrends.api.GoogleTrendsClient.execute(GoogleTrendsClient.java:75) 
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:100)
    ... 1 more
```

**Comment by elibus** [comment]
Nope. Read this: https://github.com/elibus/j-google-trends-api/issues/7
and here: https://github.com/elibus/j-google-trends-api
