### ISSUE TITLE
Cannot parse GALX!

### ISSUE THREAD

**Issue by DavidSeas** [elibus/j-google-trends-client#8]
I downloaded the last version 1.2.8 and run as example but I obtain "Cannot parse GALX!" error. I read that it has already been solved, but I continue to throw it:

This is the stack
Exception in thread "main" org.freaknet.gtrends.client.exceptions.HierarchicalDownloaderException: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
	at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:129)
	at org.freaknet.gtrends.client.App.main(App.java:81)
Caused by: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
	at org.freaknet.gtrends.api.GoogleTrendsClient.execute(GoogleTrendsClient.java:78)
	at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:100)
	... 1 more
Caused by: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Cannot parse GALX!
	at org.freaknet.gtrends.api.GoogleAuthenticator.galx(GoogleAuthenticator.java:132)
	at org.freaknet.gtrends.api.GoogleAuthenticator.authenticate(GoogleAuthenticator.java:97)
	at org.freaknet.gtrends.api.GoogleTrendsClient.execute(GoogleTrendsClient.java:65)
	... 2 more

**Comment by mainkai** [comment]
same issue here. is this still maintained?

**Comment by elibus** [comment]
@mainkai nope
